# sylvan/tensor/BUILD

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "tensor",
    hdrs = glob(["include/sylvan/tensor/**/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)
